Add notes the user must be a superuser (#143)
pg_bulkload expects that the user is a superuser.

```
# "test" is not a superuser
$ pg_bulkload sample_csv.ctl --username test --dbname test
NOTICE: BULK LOAD START
ERROR: query failed: ERROR:  must be superuser to use pg_bulkload
DETAIL: query was: SELECT * FROM pgbulkload.pg_bulkload($1)
```

Co-authored-by: Masahiro Ikeda <masahiro.ikeda.us@hco.ntt.co.jp>