Add notes the user must be a superuser
pg_bulkload expects that the user is a superuser.

```
$ pg_bulkload sample_csv.ctl --username test --dbname test
NOTICE: BULK LOAD START
ERROR: query failed: ERROR:  must be superuser to use pg_bulkload
DETAIL: query was: SELECT * FROM pgbulkload.pg_bulkload($1)
```